"""Model constants and references for nRouter SDK."""

from __future__ import annotations

# Meta Llama models
MODEL_META_LLAMA_3_3_70B_INSTRUCT = "meta/llama-3.3-70b-instruct"
MODEL_META_LLAMA_3_1_70B_INSTRUCT = "meta/llama-3.1-70b-instruct"
MODEL_META_LLAMA_3_1_8B_INSTRUCT = "meta/llama-3.1-8b-instruct"
MODEL_META_LLAMA_3_2_11B_VISION = "meta/llama-3.2-11b-vision-instruct"
MODEL_META_LLAMA_3_2_90B_VISION = "meta/llama-3.2-90b-vision-instruct"
MODEL_META_LLAMA_3_2_3B_INSTRUCT = "meta/llama-3.2-3b-instruct"
MODEL_META_LLAMA_3_2_1B_INSTRUCT = "meta/llama-3.2-1b-instruct"

# TypeSafe AI System One decision models
MODEL_TYPESAFE_JEV = "typesafe/jev"
MODEL_TYPESAFE_JEV_SYSTEM_ONE = "typesafe/jev"

# Google Gemini models
MODEL_GOOGLE_GEMINI_2_0_FLASH = "google/gemini-2.0-flash"
MODEL_GOOGLE_GEMINI_2_0_FLASH_LITE = "google/gemini-2.0-flash-lite"
MODEL_GOOGLE_GEMINI_1_5_PRO_002 = "google/gemini-1.5-pro-002"
MODEL_GOOGLE_GEMINI_1_5_FLASH_002 = "google/gemini-1.5-flash-002"

# Convenient short aliases for Gemini models
MODEL_GEMINI_2_0_FLASH = "google/gemini-2.0-flash"
MODEL_GEMINI_2_0_FLASH_LITE = "google/gemini-2.0-flash-lite"
MODEL_GEMINI_1_5_PRO_002 = "google/gemini-1.5-pro-002"
MODEL_GEMINI_1_5_FLASH_002 = "google/gemini-1.5-flash-002"

# Open-source and frontier models
MODEL_GPT_5_4_MINI = "gpt-5.4-mini"
MODEL_GPT_4O = "gpt-4o"
MODEL_GPT_4O_MINI = "gpt-4o-mini"
MODEL_CLAUDE_SONNET_4_5 = "claude-sonnet-4-5-20250929"
MODEL_CLAUDE_OPUS_4_8 = "claude-opus-4-8"

MODELS: dict[str, str] = {
    "META_LLAMA_3_3_70B_INSTRUCT": MODEL_META_LLAMA_3_3_70B_INSTRUCT,
    "META_LLAMA_3_1_70B_INSTRUCT": MODEL_META_LLAMA_3_1_70B_INSTRUCT,
    "META_LLAMA_3_1_8B_INSTRUCT": MODEL_META_LLAMA_3_1_8B_INSTRUCT,
    "META_LLAMA_3_2_11B_VISION": MODEL_META_LLAMA_3_2_11B_VISION,
    "META_LLAMA_3_2_90B_VISION": MODEL_META_LLAMA_3_2_90B_VISION,
    "META_LLAMA_3_2_3B_INSTRUCT": MODEL_META_LLAMA_3_2_3B_INSTRUCT,
    "META_LLAMA_3_2_1B_INSTRUCT": MODEL_META_LLAMA_3_2_1B_INSTRUCT,
    "TYPESAFE_JEV": MODEL_TYPESAFE_JEV,
    "TYPESAFE_JEV_SYSTEM_ONE": MODEL_TYPESAFE_JEV_SYSTEM_ONE,
    "GOOGLE_GEMINI_2_0_FLASH": MODEL_GOOGLE_GEMINI_2_0_FLASH,
    "GOOGLE_GEMINI_2_0_FLASH_LITE": MODEL_GOOGLE_GEMINI_2_0_FLASH_LITE,
    "GOOGLE_GEMINI_1_5_PRO_002": MODEL_GOOGLE_GEMINI_1_5_PRO_002,
    "GOOGLE_GEMINI_1_5_FLASH_002": MODEL_GOOGLE_GEMINI_1_5_FLASH_002,
    "GEMINI_2_0_FLASH": MODEL_GOOGLE_GEMINI_2_0_FLASH,
    "GEMINI_2_0_FLASH_LITE": MODEL_GOOGLE_GEMINI_2_0_FLASH_LITE,
    "GEMINI_1_5_PRO_002": MODEL_GOOGLE_GEMINI_1_5_PRO_002,
    "GEMINI_1_5_FLASH_002": MODEL_GOOGLE_GEMINI_1_5_FLASH_002,
    "GPT_5_4_MINI": MODEL_GPT_5_4_MINI,
    "GPT_4O": MODEL_GPT_4O,
    "GPT_4O_MINI": MODEL_GPT_4O_MINI,
    "CLAUDE_SONNET_4_5": MODEL_CLAUDE_SONNET_4_5,
    "CLAUDE_OPUS_4_8": MODEL_CLAUDE_OPUS_4_8,
}

__all__ = [
    "MODELS",
    "MODEL_META_LLAMA_3_3_70B_INSTRUCT",
    "MODEL_META_LLAMA_3_1_70B_INSTRUCT",
    "MODEL_META_LLAMA_3_1_8B_INSTRUCT",
    "MODEL_META_LLAMA_3_2_11B_VISION",
    "MODEL_META_LLAMA_3_2_90B_VISION",
    "MODEL_META_LLAMA_3_2_3B_INSTRUCT",
    "MODEL_META_LLAMA_3_2_1B_INSTRUCT",
    "MODEL_TYPESAFE_JEV",
    "MODEL_TYPESAFE_JEV_SYSTEM_ONE",
    "MODEL_GOOGLE_GEMINI_2_0_FLASH",
    "MODEL_GOOGLE_GEMINI_2_0_FLASH_LITE",
    "MODEL_GOOGLE_GEMINI_1_5_PRO_002",
    "MODEL_GOOGLE_GEMINI_1_5_FLASH_002",
    "MODEL_GEMINI_2_0_FLASH",
    "MODEL_GEMINI_2_0_FLASH_LITE",
    "MODEL_GEMINI_1_5_PRO_002",
    "MODEL_GEMINI_1_5_FLASH_002",
    "MODEL_GPT_5_4_MINI",
    "MODEL_GPT_4O",
    "MODEL_GPT_4O_MINI",
    "MODEL_CLAUDE_SONNET_4_5",
    "MODEL_CLAUDE_OPUS_4_8",
]
